# Specifies the secret data for imagePullSecrets needed to fetch the private docker images
imageCredentials:
  name: giantswarm-partner-aqua-pull-secret
  repositoryUriPrefix: "quay.io" 

rbac:
  enabled: true
  privileged: true
  roleRef:

clustermode: false

admin:
  token:
  password:
  secretname: null
  tokenkey: null
  passwordkey: null

dockerless: false

db:
  external:
    enabled: false
    name:
    host:
    port:
    user:
    password:
    auditName:
    auditHost:
    auditPort:
    auditUser:
    auditPassword:
  passwordSecret: null
  dbPasswordName: null
  dbPasswordKey: null
  dbAuditPasswordName: null
  dbAuditPasswordKey: null
  ssl: false
  auditssl: false
  image:
    repository: giantswarm/aqua-database
    tag: "4.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  persistence:
    enabled: true
    storageClass:
    size: 30Gi
    accessMode: ReadWriteOnce
  livenessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host $POD_IP
    initialDelaySeconds: 60
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host $POD_IP
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
  resources:
    requests:
      cpu: 0.1
      memory: 0.2Gi
    limits:
      cpu: 1
      memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}

gate:
  image:
    repository: giantswarm/aqua-gateway
    tag: "4.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 3622
  publicIP: aqua-gateway
  replicaCount: 1
  ingress:
    enabled: false
    annotations: 
      kubernetes.io/ingress.class: nginx
    hosts: #REQUIRED
    #- aquasec-test.example.com
    tls: []
    #  - secretName: aquasec-tls
    #    hosts:
    #      - aquasec.domain.com
  livenessProbe: {}
  readinessProbe: {}
  resources:
    requests:
      cpu: 0.1
      memory: 0.2Gi
    limits:
      cpu: 1
      memory: 2Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}

web:
  image:
    repository: giantswarm/aqua-console
    tag: "4.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 8080
  encryptionKey:
  ingress:
    enabled: false
    annotations: 
      kubernetes.io/ingress.class: nginx
    hosts: #REQUIRED
    #- aquasec-test.example.com
    tls: []
    #  - secretName: aquasec-tls
    #    hosts:
    #      - aquasec.domain.com
  replicaCount: 1
  livenessProbe: {}
  readinessProbe: {}
  persistence:
    storageClass:
    size: 4
    accessMode: ReadWriteOnce
  resources:
    requests:
      cpu: 0.1
      memory: 0.2Gi
    limits:
      cpu: 1
      memory: 2Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  proxy:
    httpProxy:
    httpsProxy:
    noProxy:

scanner:
  enabled: false
  image:
    repository: giantswarm/aqua-scanner
    tag: "4.2"
    pullPolicy: IfNotPresent
  user:
  password:
  replicaCount: 1
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
