---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-svc
  labels:
    app: {{ .Release.Name }}-gateway
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.gate.service.type }}
  {{- if eq .Values.gate.service.type "LoadBalancer" }}
  loadBalancerSourceRanges:
{{ toYaml .Values.gate.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-gateway
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: aqua-health
  - port: {{ .Values.gate.service.externalPort }}
    targetPort: 3622
    protocol: TCP
    name: aqua-gate
  - port: 8443
    protocol: TCP
    targetPort: 8443
    name: aqua-gate-ssl