imageCredentials:
  name: giantswarm-partner-aqua-pull-secret
  repositoryUriPrefix: "quay.io"

enforcerToken: ""

enforcerTokenSecretName: null
enforcerTokenSecretKey: null
enforcerLogicalName:

memoryPressure:
networkFailMode:

privileged: true

runcInterception: true
sendingHostImagesDisables: false

scanningMemoryLimit: 300

grpcKeepAliveInterval: 30

rbac:
  enabled: true
  roleRef:

gate:
  host: server-gateway-svc
  port: 3622

image:
  repository: giantswarm/aqua-enforcer
  tag: 4.6.20236
  pullPolicy: IfNotPresent

livenessProbe: {}
readinessProbe: {}
resources:
  limits:
    memory: 1500Mi
  requests:
    memory: 1500Mi
nodeSelector: {}
tolerations: []
