imageCredentials:
  create: false
  name: giantswarm-partner-aqua-pull-secret
  repositoryUriPrefix: "quay.io"
  registry: "quay.io"

  username: ""
  password: ""

enforcerToken: ""

enforcerTokenSecretName: null
enforcerTokenSecretKey: null
enforcerLogicalName:

logLevel:

securityContext:
  privileged: true
  # Note: enforcer deployment in non privileged mode https://docs.aquasec.com/docs/enforcer-deployment-in-non-privileged-mode#kubernetes-deployments
  # privileged: false
  # capabilities:
  #   add:
  #     - SYS_ADMIN
  #     - NET_ADMIN
  #     - NET_RAW
  #     - SYS_PTRACE
  #     - KILL
  #     - MKNOD
  #     - SETGID
  #     - SETUID
  #     - SYS_MODULE
  #     - AUDIT_CONTROL
  #     - SYSLOG
  #     - SYS_CHROOT

hostRunPath:  # pks - /var/vcap/sys/run/docker

rbac:
  enabled: true
  roleRef:

gate:
  host: aqua-gateway-svc  # for envoy deployment use host for aqua-lb and port 443
  port: 8443

image:
  repository: giantswarm/aqua-enforcer
  tag: "5.3"
  pullPolicy: IfNotPresent

livenessProbe: {}
readinessProbe: {}
resources: {}
  # Note: For recommendations please check the official sizing guide.
  # requests:
  #   cpu: 350
  #   memory: 0.512Gi
  # limits:
  #   cpu: 1500
  #   memory: 1.5Gi
nodeSelector: {}
tolerations: []

# extraEnvironmentVars is a list of extra enviroment variables to set in the enforcer daemonset.
# https://docs.aquasec.com/docs/enforcer-optional-variables
extraEnvironmentVars: {}
  # ENV_NAME: value
  # AQUA_TLS_VERIFY: true
  # AQUA_PUBLIC_KEY: "/etc/ssl/custom-certificates/agent.crt"
  # AQUA_PRIVATE_KEY: "/etc/ssl/custom-certificates/agent.key"
  # AQUA_ROOT_CA: "/etc/ssl/custom-certificates/aqua-ca.pem"

# extraSecretEnvironmentVars is a list of extra enviroment variables to set in the enforcer daemonset.
# These variables take value from existing Secret objects.
extraSecretEnvironmentVars: []
  # - envName: ENV_NAME
  #   secretName: name
  #   secretKey: key

envoy:
  enabled: false
  configMap:
