imageCredentials:
  name: giantswarm-partner-aqua-pull-secret
  repositoryUriPrefix: "quay.io"

enforcerToken: ""

enforcerTokenSecretName: null
enforcerTokenSecretKey: null
enforcerLogicalName:

memoryPressure:
networkFailMode:

privileged: true

runcInterception: true
sendingHostImagesDisables: false

scanningMemoryLimit: 500

rbac:
  enabled: true
  roleRef:

gate:
  host: server-gateway-svc
  port: 3622

image:
  repository: giantswarm/aqua-enforcer
  tag: 4.6.20156
  pullPolicy: IfNotPresent

livenessProbe: {}
readinessProbe: {}
resources:
  {}
  # limits:
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
nodeSelector: {}
tolerations: []
