{{- if .Values.rbac.enabled -}}
{{- if not .Values.rbac.roleRef }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
    name: {{ .Release.Name }}-psp
    labels:
      app: {{ .Release.Name }}
      chart: "{{ include "scanner.chartVersion" . }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - secret
  - configMap
  - hostPath
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-cluster-role
  labels:
    app: {{ .Release.Name }}
    chart: "{{ include "scanner.chartVersion" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ["extensions"]
  resourceNames: [{{ .Release.Name }}-psp]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
{{- end }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ include "scanner.chartVersion" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.roleRef }}
  name: {{ .Values.rbac.roleRef }}
  {{- else }}
  name: {{ .Release.Name }}-cluster-role
  {{- end }}
{{- end }}
