---
{{- if not .Values.serviceAccount}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app: {{ .Release.Name }}
    chart: "{{ include "scanner.chartVersion" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
imagePullSecrets:
- name: {{ .Values.imageCredentials.name }}
{{- end }}