{{- if not .Values.enforcerTokenSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-token
  labels:
    app: {{ .Release.Name }}-token
    chart: "{{ include "chartVersion" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  token: {{ (required "A valid .Values.enforcerToken entry required!" .Values.enforcerToken) | b64enc }}
{{- end }}