---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app: {{ .Release.Name }}
    chart: "{{ include "chartVersion" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
imagePullSecrets:
{{- if .Values.imageCredentials.create }}
- name: {{ .Release.Name }}-registry-secret
{{- else }}
- name: {{ .Values.imageCredentials.name }}
{{- end }}
